omnibus:
  chef_version: 13.2.20
network:
  private_network:
    ip: 192.168.33.101
    comments:
      - "TIP: the static IP must not collide with other machines on the same network"
berkself:
  cookbooks:
    apt: ~> 6.1.3
    timezone_iii: ~> 1.0.4
    nodenv: ~> 0.1.2
chef:
  recipes:
    - apt
    - timezone_iii
    - nodenv
  json:
    timezone: UTC
    nodenv:
      user_installs:
        - user: vagrant
          nodes:
            - 6.11.2
require:
  vagrant-plugins:
    - vagrant-omnibus
    - vagrant-berkshelf
