omnibus:
  chef_version: 13.2.20
network:
  private_network:
    ip: 192.168.33.101
    comments:
      - "TIP: the static IP must not collide with other machines on the same network"
berkself:
  cookbooks:
    apt: ~> 6.1.0
    timezone_iii: ~> 1.0.4
    ruby_rbenv: ~> 1.2.0
    nodejs: ~> 4.0.0
    postgresql: ~> 6.1.1
chef:
  recipes:
    - apt
    - timezone_iii
    - ruby_build
    - ruby_rbenv::user
    - nodejs
    - postgresql::server
  json:
    timezone: UTC
    rbenv:
      user_installs:
        - user: vagrant
          rubies:
            - 2.4.1
          global: 2.4.1
          gems:
            2.4.1:
              - name: bundler
    postgresql:
      password:
        postgres: password
require:
  vagrant-plugins:
    - vagrant-omnibus
    - vagrant-berkshelf
