omnibus:
  chef_version: 13.2.20
berkself:
  cookbooks:
    apt: ~> 6.1.0
    ruby_rbenv: ~> 1.2.0
chef:
  recipes:
    - apt
    - ruby_build
    - ruby_rbenv::user
  json:
    rbenv:
      user_installs:
        - user: vagrant
          rubies:
            - 2.3.4
          global: 2.3.4
          gems:
            2.3.4:
              - name: bundler
require:
  vagrant-plugins:
    - vagrant-omnibus
    - vagrant-berkshelf
